"""Generate private MC402 half-band taps; no circuit values are fitted here."""

from pathlib import Path
import numpy as np
from scipy.signal import remez

ROOT = Path(__file__).resolve().parents[5]
DESTINATION = ROOT / "dsp" / "MC402HalfBandCoefficients.h"


def taps(length, edge):
    h = remez(
        length, [0, edge, 0.5 - edge, 0.5], [1, 0], fs=1, maxiter=200, grid_density=64
    )
    # Exact half-band sparsity, symmetry and DC unity after remez rounding.
    h = (h + h[::-1]) * 0.5
    h[::2] = 0
    h[length // 2] = 0.5
    h[1::2] *= 0.5 / h[1::2].sum()
    return h


def main():
    parts = [
        "#pragma once",
        "",
        "// Generated by references/pedals/mc402/m1/tools/generate_fir.py.",
        "// Equiripple half-band; frequencies in cycles per high-rate sample.",
        "// 65 taps: pass 0..0.20, stop 0.30..0.50; 33 taps: 0..0.15, 0.35..0.50.",
        "#include <array>",
        "",
        "namespace holdsworth::dsp::mc402_detail",
        "{",
    ]
    for length, edge in [(65, 0.20), (33, 0.15)]:
        parts.append(
            f"inline constexpr std::array<double, {length}> kHalfBand{length}{{"
        )
        parts.extend(f"  {value:.17g}," for value in taps(length, edge))
        parts.append("};")
    parts.append("} // namespace holdsworth::dsp::mc402_detail\n")
    DESTINATION.write_text("\n".join(parts))
    print(DESTINATION)


if __name__ == "__main__":
    main()
